CastleApps/CastleApps/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apartments.urls')),
    path('users/',include('users.urls'))
]

CastleApps/apartments/urls.py
from . import views
from django.urls import path

urlpatterns = [
    # Our mainpage
    path('', views.home, name='frontpage'),

    # Paths below are available to everyone
    path('price_list/', views.priceList, name='priceList'),
    path('company_history/', views.companyHistory, name='companyHistory'),

    # Page below is for ajax search
    path('all_apartments/',
         views.allApartments, name="apartment_list"),

    # Search form on frontpage
    path('search_results/', views.searchApartments, name="search-results"),

    # This should lead to a listing
    path('apartments/<int:apartmentID>/',
         views.singleApartment, name="apartment"),

    path('employee_all_apartments/',
         views.employeeAllApartments, name="employee_apartment_list"),

    # Admin paths:
    path('apartments/<int:locationID>/create_apartment', views.createApartments, name="create-apartment"),
    path('create_location', views.createLocation, name="create-location"),
    path('apartments/<int:apartmentID>/edit_apartment', views.editApartment, name="edit-apartment"),
    path('apartments/<int:apartmentID>/add_listing/', views.addListing, name="add-listing"),
    path('apartments/<int:apartmentID>/remove_listing/', views.removeListing, name="add-listing"),
    path('apartments/<int:apartmentID>/remove_apartment/', views.removeApartment, name="remove-apartment"),
    path('apartments/<int:apartmentID>/add_key_distances/', views.addKeyDistances, name="add_key_distances"),
    path('apartments/<int:apartmentID>/add_image/', views.addImage, name="add-image"),
    path('apartments/<int:apartmentID>/payment_info', views.addPaymentInfo, name="pay_info"),
    path('apartments/<int:apartmentID>/payment_info/<listingID>/<int:paymentID>/review', views.reviewPayment,
         name="review"),
    path('apartments/<int:apartmentID>/add_open_house/', views.openHouseListing, name="open_house")
]

CastleApps/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

urlpatterns = [
    path('register', views.register, name="register"),
    path('login', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout', LogoutView.as_view(next_page='login'), name='logout'),
    path('<int:userID>/view_profile', views.viewProfile, name='viewProfile'),
    path('<int:userID>/edit_profile', views.editProfile, name='editProfile'),
    path('<int:userID>/view_history', views.viewHistory, name='view_history'),
    # Here we have a list of employees page -> Should lead to their profile if clicked on
    path('agents/', views.agents, name='agents'),
    # Path leads to a single users in our system
    path('<int:userID>/', views.singleUser, name="users"),
    path('contact-us', views.contactUs, name="contact_us"),
    # path('users', include('users.urls')),
    # path('users', include('django.contrib.auth.urls')),
    path('<int:userID>/owned_apartments', views.ownedApartments, name="owned_apartments"),
    path('users/<int:userID>/managed_apartments', views.managedApartments, name="managed_apartments"),
]

CastleApps/apartments/models.py
# Create your models here.
from django.db import models  # Tells it to map to database
from django.utils import timezone
from django.conf import settings


# You do not need to specify primary key. It is automatically
# generated and auto incremented

# Steps to update the Database
# makemigrations apartments
# migrate apartments
# sqlmigrate apartments 0001_initial
# migrate

# Our model.py was designed with the ID being auto generated in mind.

# Location is a general place to be able to better normalize the data.


# In the model.py we decided to break our own rules when it comes to variables
# We did this to make it easier for us to access the Database through the Django code
# So we did not have to worry about capitalization
class Country(models.Model):
    country = models.CharField(primary_key=True, max_length=100)
    def __str__(self):
        return self.country

class Locations(models.Model):
    city = models.CharField(max_length=100, blank=True, null=True)
    region = models.CharField(max_length=50)
    zip = models.CharField(max_length=15)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.country)

# Apartments is general information about the apartment that is only inserted once
class Apartments(models.Model):
    registration = models.CharField(max_length=100, unique=True)
    address = models.CharField(max_length=50)
    size = models.IntegerField(max_length=50)
    rooms = models.IntegerField(max_length=50)
    bathrooms = models.IntegerField(max_length=50)
    type = models.CharField(max_length=50, default="Apartment")
    aptsuite = models.CharField(blank=True, null=True, max_length=30)
    timeofconstruction = models.CharField(max_length=50, default=2000)
    displayimage = models.CharField(max_length=5000)
    forsale = models.BooleanField(default=False, blank=True, null=True)
    locationid = models.ForeignKey(Locations, on_delete=models.CASCADE, )  # Foreign keys are singular. While the table
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


# Apartments usually have many images associated with them
class ApartmentImages(models.Model):
    image = models.CharField(max_length=5000)
    aid = models.ForeignKey(Apartments, on_delete=models.CASCADE)
    def __str__(self):
        return self.image

# Each apartments has a listing. It can have many listings.
# Same apartment can only have one listing up at a time though!
class Listings(models.Model):
    price = models.IntegerField(max_length=200)
    description = models.TextField()
    registered = models.DateTimeField(default=timezone.now)
    soldondate = models.DateTimeField(default=None, blank=True, null=True)
    agent = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    apartmentid = models.ForeignKey(Apartments, on_delete=models.CASCADE)

    @property
    def shortMortgage(self):
        price = int(self.price)
        priceAfterDownPayment = price * 0.85  # We assume people put 15% down
        return (priceAfterDownPayment / 120) + (0.05 / 12 * priceAfterDownPayment)

    @property
    def mediumMortgage(self):
        price = int(self.price)
        priceAfterDownPayment = price * 0.85  # We assume people put 15% down
        return (priceAfterDownPayment / 240) + (0.05 / 12 * priceAfterDownPayment)

    @property
    def longMortgage(self):
        price = int(self.price)
        priceAfterDownPayment = price * 0.85  # We assume people put 15% down
        return (priceAfterDownPayment / 360) + (0.05 / 12 * priceAfterDownPayment)


# We use this to register the open houses. THese are displayed on the front page.
class OpenHouse(models.Model):
    openhousestart = models.DateTimeField(default=None, max_length=75)
    openhouseend = models.DateTimeField(default=None, max_length=75)
    listingid = models.ForeignKey(Listings, on_delete=models.CASCADE)


# These are small things as the table names suggest. We display this after an apartment has been
# Listed for sale you can add distance to supermarket etc.
class ListingMiscs(models.Model):
    footpreschool = models.CharField(max_length=5, blank=True, null=True)
    carpreschool = models.CharField(max_length=5, blank=True, null=True)
    footbusstop = models.CharField(max_length=5, blank=True, null=True)
    carbusstop = models.CharField(max_length=5, blank=True, null=True)
    carsupermarket = models.CharField(max_length=5, blank=True, null=True)
    footsupermarket = models.CharField(max_length=5, blank=True, null=True)
    footmetro = models.CharField(max_length=5, blank=True, null=True)
    carmetro = models.CharField(max_length=5, blank=True, null=True)
    listingid = models.ForeignKey(Listings, on_delete=models.CASCADE)


# Each apartment can have many documents attached to them. repair bills/copy of deed and more
class ListingDocs(models.Model):
    attachment = models.CharField(max_length=500, default=None)
    description = models.CharField(max_length=500, default=None)
    listingid = models.ForeignKey(Listings, on_delete=models.CASCADE)


# Used to calculate the final price and used to display the list on our website
class PriceLists(models.Model):
    salescost = models.CharField(max_length=20)
    appraisalcost = models.CharField(max_length=15)
    photocost = models.CharField(max_length=15)
    managementcost = models.CharField(max_length=15)
    datacollection = models.CharField(max_length=15)


class Transactions(models.Model):
    price = models.CharField(max_length=4000)
    date = models.DateField()
    isseller = models.BooleanField()
    listingid = models.ForeignKey(Listings, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

# All the information necessary to make a purchase on our platform
class PaymentInfos(models.Model):
    cardnumber = models.CharField(max_length=30)
    cardholder = models.CharField(max_length=80)
    expmonth = models.CharField(max_length=50)
    expyear = models.CharField(max_length=50)
    city = models.CharField(max_length=80)
    address = models.CharField(max_length=80)
    aptsuite = models.CharField(max_length=20, default=None, blank=True, null=True)
    zip = models.CharField(max_length=80)
    ssn = models.CharField(max_length=40)
    isreviewed = models.BooleanField(default=False, blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


# The contact form being used on the front page down to the right
# Sends an AJAX request.
class ContactForm(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    description = models.TextField(max_length=1000)




class ViewHistory(models.Model):
    apartmentid = models.ForeignKey(Apartments, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class CompanyInformation(models.Model):
    name = models.CharField(max_length=50)
    logo = models.CharField(max_length=5000)
    backgroundPhoto = models.CharField(max_length=5000)
    phone = models.CharField(max_length=15)
    email = models.CharField(max_length=100)
    officeHours = models.CharField(max_length=40)

CastleApps/apartments/forms/apartment_form.py
from django.forms import ModelForm, widgets
from ..models import Apartments, ApartmentImages
from django import forms


class CastleAppsCreateForm(ModelForm):
    class Meta:
        image = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
        model = Apartments
        exclude = ['id', 'forsale']
        widgets = {

            'registration': widgets.TextInput(attrs={'class': 'form-control'}),
            'address': widgets.TextInput(attrs={'class': 'form-control'}),
            'aptsuite': widgets.TextInput(attrs={'class': 'form-control'}),
            'size': widgets.NumberInput(attrs={'class': 'form-control'}),
            'rooms': widgets.NumberInput(attrs={'class': 'form-control'}),
            'bathrooms': widgets.NumberInput(attrs={'class': 'form-control'}),
            'timeofconstruction': widgets.TextInput(attrs={'class': 'form-control'}),
            'type': widgets.TextInput(attrs={'class': 'form-control'}),
            'owner': widgets.TextInput(attrs={'class': 'form-control'})

        }


class EditAppForm(ModelForm):
    class Meta:
        model = Apartments
        exclude = ['id', 'forsale']
        widgets = {
            'registration': widgets.TextInput(attrs={'class': 'form-control'}),
            'address': widgets.TextInput(attrs={'class': 'form-control'}),
            'aptsuite': widgets.TextInput(attrs={'class': 'form-control'}),
            'size': widgets.NumberInput(attrs={'class': 'form-control'}),
            'rooms': widgets.NumberInput(attrs={'class': 'form-control'}),
            'bathrooms': widgets.NumberInput(attrs={'class': 'form-control'}),
            'timeofconstruction': widgets.TextInput(attrs={'class': 'form-control'}),
            'type': widgets.TextInput(attrs={'class': 'form-control'}),
            'owner': widgets.TextInput(attrs={'class': 'form-control'})
        }


class AddImage(ModelForm):
    class Meta:
        model = ApartmentImages
        exclude = ['id', 'aid']
        image = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))

CastleApps/users/views.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

from users.forms import UsersCreationForm, EditProfileForm


from django.http import HttpResponse
# Create your views here.
from apartments.models import *
from users.models import *
from django.shortcuts import get_object_or_404, render, redirect

from django.contrib.auth.decorators import login_required



Users = get_user_model()
# Create your views here.


def register(request):
    if request.method == 'POST':
        form = UsersCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')

    return render(request, 'users/register.html', {
        'form': UserCreationForm()
    })


@login_required
def editProfile(request):
    if request.method == 'POST':
        form = UserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users/', request.user)


def viewProfile(request, userID=None):
    if userID:
        user = Users.objects.get(pk=userID)
    else:

        user = request.user
    context = {'user': user}
    return render(request, 'users/user_profile.html', context)



#
def agents(request):
    # Checks if the person in the Users table is staff
    users = Users.objects.filter(is_staff=True)
    # Simply returns every users that returned true as staff
    # HTML will then loop through the users that are part of the staff and display them
    context = {
        'users': users
    }
    return render(request, 'users/agents.html', context)


# Here you can display a single users
def singleUser(request, userID):

    user = get_object_or_404(Users, pk=userID)

    if user.is_staff is False:
        apartments = Apartments.objects.filter(owner_id=userID, forsale=True)
        context = {
            'user': user,
            'apartments': apartments
        }
        return render(request, 'users/user_profile.html', context)
    listingsOfApartments = Listings.objects.filter(agent_id=userID)
    pkOfApps = []
    for x in listingsOfApartments:
        print(x.apartmentid_id)
        pkOfApps.append(x.apartmentid_id)
    apartments = Apartments.objects.filter(id__in=pkOfApps, forsale =True)
    context = {
        'user': user,
        'apartments': apartments
    }
    return render(request, 'users/single_employee.html', context)


def viewHistory(request, userID):
    user = request.user
    if user.id != userID:
        return HttpResponse('Unauthorized', status=401)
    newList = []
    history = ViewHistory.objects.filter(user_id=userID)
    for x in history:
        newList.append(x.apartmentid_id)
    helloGo = Apartments.objects.filter(id__in=newList)[0:6]
    context = {
        'apartments': helloGo
    }
    return render(request, 'users/view_history.html', context)


def ownedApartments(request, userID):
    user = request.user
    if user.id != userID:
        return HttpResponse('Unauthorized', status=401)
    apartments = Apartments.objects.filter(owner_id=userID)
    context = {
        'apartments': apartments
    }
    return render(request, 'users/owned_apartments.html', context)


def managedApartments(request, userID):
    #listings = Listings.objects.filter(agent_id=userID)
    listingsOfApartments = Listings.objects.filter(agent_id=userID)
    pkOfApps = []
    for x in listingsOfApartments:
        print(x.apartmentid_id)
        pkOfApps.append(x.apartmentid_id)
    apartments = Apartments.objects.filter(id__in=pkOfApps, forsale=True)

    context = {
        'apartments': apartments
    }
    print("DSKFDSJFJDSFJDSFJDSF", apartments)
    return render(request, 'users/managed_apartments.html', context)


@login_required
def editProfile(request, userID):
    user = request.user
    if user.id != userID:
        return HttpResponse('Unauthorized', status=401)
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('frontpage')
    else:
        form = EditProfileForm(instance=request.user)
        context = {'form': form}
        return render(request, 'users/edit_profile.html', context)


def contactUs(request):
    print("START OF CONTACTUS VIEW FUNCTION")
    if request.method == "POST":
        print("GETTING PARAMS")
        name = request.POST.get('name')
        email = request.POST.get('email')
        msg = request.POST.get('description')
        print("PRINTING PARAMS", name, email, msg)
        print("POSTING TO DB")
        ContactForm.objects.create(name=name, email=email, description=msg)
        return HttpResponse(status=201)

CastleApps/templates/apartments/about.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/about.css' %}">
{% endblock css %}
{% block content %}
<div class="employees">
    <div class="container">
    {{ employees.startDate }}
        {% for employee in employees %}
        <div class="item">
            <div class = employeeDescriptions> {{ employee.user.firstName }}</div>
            <h3>{{employee.description}} {{employee.startDate}}</h3>
            <div class="meta">{{employee.user.firstName}} {{employee.user.lastName}} {{ employee.user.email }}</div>
            <div class="desc">
                <img class = employeePicture src =  " {{ employee.user.profileImagePath }}"/>
                <p>{{users.phone}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

CastleApps/templates/apartments/add_image.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="heading">
            <h2>Add An Image </h2>
        </div>
        <form action="{% url 'add-image' apartmentID %}" class="white-background" method="POST">
            {% csrf_token %}
             {% for item in form %}
                <div class="form-group">
                    <label>{{item.name}}</label>
                    {{item}}
                </div>
            {% endfor %}
            <input type="submit" value="Upload" class="btn btn-primary pull-right" style="clear:both; margin : 10px 0" />
            <a href="/apartments/{{ apartmentID }}" class="btn btn-primary pull right">Back</a>
        </form>
    </div>
{% endblock %}

CastleApps/templates/apartments/add_open_house.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="heading">
            <h2>Add Open House</h2>
        </div>
        <form action="{% url 'open_house' apartmentID %}" class="white-background" method="POST">
            {% csrf_token %}
             {% for item in form %}
                <div class="form-group">
                    <label>{{item.name}}</label>
                    {{item}}
                </div>
            {% endfor %}
            <input type="submit" value="Create" class="btn btn-primary pull-right" style="clear:both; margin : 10px 0" />
        </form>
    </div>
{% endblock %}

CastleApps/templates/apartments/buy_now.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
<link rel="stylesheet" href="{% static 'css/apartments.css' %}">
<link rel="stylesheet" href="{% static 'css/agents.css' %}">
{% endblock css %}
{% block content %}

<div class="apartment single">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="heading">
                    <h2>{{listing.apartmentid.address}} in {% if listing.apartmentid.locationid.city %}{{ listing.apartmentid.locationid.city }}{% endif %}, {{listing.apartmentid.locationid.zip}}, {{listing.apartmentid.locationid.country}}</h2>
                </div>
                <div class="images">
                          <div class="image-list owl-carousel">
                        <div class="image active">
                            <img src="{{apartment.displayimage}}">
                        </div>
                        {%  for image in images %}
                            <div class="image">
                                <img src="{{ image }}" alt="Image here" srcset="">
                            </div>
                        {%  endfor %}
                    </div>
                </div>
                 <div class="heading">
                    <h3 style="font-size: 24px; font-weight: 500; font-style: italic; margin-bottom: 15px;">Review</h3>
            </div>
         <div class="col-md-6">
                <div class="meta">
                    <div class="info">
                        <p> price: &euro;{{ listing.price }}</p>
                    </div>
                </div>
            </div>
        </div>

{#    <div>Location id: {{ locationID }}</div>#}
        <form action="{% url 'pay_info' listing.apartmentid.id %}" class="white-background" method="POST" autocomplete="on">
            {% csrf_token %}
             {% for item in form %}
                <div class="form-group">
                    {% if item.field.widget.input_type != 'select' %}
                        <label>{{item.name}}</label>
                    {% endif %}
                    {{item}}
                </div>
            {% endfor %}
            <input type="submit" value="Next" class="btn btn-primary pull-right" style="clear:both; margin : 10px 0" />
        </form>
        </div>
    </div>
{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
<script src="{% static '/js/sliders.js' %}"></script>
{% endblock %}

{% endblock %}

CastleApps/templates/apartments/company_history.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/about.css' %}">
{% endblock css %}
{% block content %}
<div class="history">
    <div class="container">
        <div class="heading" style="margin-bottom: 50px;">
            <h2>We are a brand new company started fresh in 2019.</h2>  
        </div>
        <div class="text">
            <p>Founded in 1875 with a mission of providing excellent selection of fine houses to the great people of Western France.</p>
            <p>Now an international company hoping to bring the world the same great personal and intuitive service we provide those years ago.</p>
            <p>With a growing business came challenges of getting the best people.</p>
            <p>But, I can assure you. We have the best people. People everywhere want to work for us.</p>
            <p>As a matter of fact the other day I was talking to someone and she said.</p>
            <p>“Hey Castle Apartments how do you get the best people?” I said I get them and I take them. If they are not the best people then I do not want them. I send them back. And whoever sent them  should pay to build my apartments.</p>
            <p>Finally, we make the best deals and pass it on to you. The seller and the buyer!</p>
        </div>
    </div>
</div>
{% endblock content %}

CastleApps/templates/apartments/home.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
<link rel="stylesheet" href="{% static '/css/apartments.css' %}">
<link rel="stylesheet" href="{% static '/css/banner.css' %}">
{% endblock css %}
{% block banner %}
<div class="frontpage-banner">
    <div class="absolute">
        <h1>Welcome to Castle Apartments</h1>
    </div>

    <span class="arrow"></span>
</div>
{% endblock %}
{% block content %}
<div class="apartments">
    <div class="container">
        <h2>Open houses</h2>
        <div class="apartments-wrapper slider owl-carousel">
            {% for apartment in apartments %}
                {% if apartment.forsale %}

            <div class="apartment">
                <div class="header">
                    <div class="type">{{apartment.type}} in {{apartment.locationid.region}} <div class="country">{{apartment.locationid.country}}</div></div>
                    <div class="rooms">
                        <div class="room bedroom">
                            <div class="total">
                                {{apartment.rooms}}
                            </div>
                            <div class="icon">
                                <img src="/static/img/bed.svg" />
                            </div>
                        </div>
                        <div class="room bathroom">
                            <div class="total">
                                    {{apartment.bathrooms}}
                            </div>
                            <div class="icon">
                                <img src="/static/img/bathtub.svg" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="image">
                    <a href="/apartments/{{apartment.id}}">
                        <img src="{{ apartment.displayimage }}" alt="Image here" srcset="">
                    </a>
                </div>
                <div class="meta">
                    <div class="header">
                        <div class="price">&euro; {{apartment.listings_set.first.price}}</div>
                        <div class="size">{{apartment.size}} m&sup2;</div>
                    </div>
                    <div class="desc">
                        {{apartment.listings_set.first.description}}
                    </div>
                </div>
            </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

<div class="apartments">
    <div class="container">
        <h2>New Listing</h2>
        <div class="apartments-wrapper row">
            {% for apartment in newlyListed reversed %}
            <div class="col-md-4">
                <div class="apartment">
                    <div class="header">
                        <div class="type">{{apartment.type}} in {{apartment.locationid.region}} <div class="country">{{apartment.locationid.country}}</div></div>
                        <div class="rooms">
                            <div class="room bedroom">
                                <div class="total">
                                    {{apartment.rooms}}
                                </div>
                                <div class="icon">
                                    <img src="/static/img/bed.svg" />
                                </div>
                            </div>
                            <div class="room bathroom">
                                <div class="total">{{apartment.bathrooms}}</div>
                                <div class="icon">
                                    <img src="/static/img/bathtub.svg" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="image">
                        <a href="/apartments/{{apartment.id}}">
                            <img src="{{ apartment.displayimage }}" alt="Image here" srcset="">
                        </a>
                    </div>
                    <div class="meta">
                        <div class="header">
                            <div class="price">&euro; {{apartment.listings_set.first.price}}</div>
                            <div class="size">{{apartment.size}} m&sup2;</div>
                        </div>
                        <div class="desc">
                            {{apartment.listings_set.first.description}}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}
{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
<script src="{% static '/js/sliders.js' %}"></script>
{% endblock%}

CastleApps/templates/apartments/purchase_status.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1> git commit</h1>
</body>
</html>

CastleApps/templates/apartments/single_user.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/agents.css' %}">
{% endblock css %}
{% block content%}
<div class="container">
    <h1> A seller</h1>
    <div class="agent">
        <div class="image">
            <img src="{{user.profileimagepath}}" alt="">
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="location">
                    <h2>{{apartment.address}}</h2>

                </div>
            </div>
            <div class="col-md-6">
                <div class="meta">
                    <p>Username: {{ user.username }}</p>
                    <p>First name: {{user.first_name}}</p>
                    <p>Last name: {{user.last_name}}</p>
                    <p>Last Login: {{user.last_login}}</p>

                    {%  for image in images %}
                        <img src="{{ image }}" alt="Image here" srcset="">
                    {%  endfor %}

                        <h2>{{ user.first_name }} {{ user.last_name }} has these listed for sale: </h2>
        <div class="apartments-wrapper slider owl-carousel">
            {% for apartment in apartments %}

            <div class="apartment">
                <div class="image">
                    <a href="/apartments/{{apartment.id}}">


                        <img src="{{ apartment.displayimage }}" alt="Image here" srcset="">
                    </a>
                    <div>
                            {{ apartment.listings_set.last.openhouse_set.last.openhousestart }} -
                            {{ apartment.listings_set.last.openhouse_set.last.openhouseend }}
                        </div>
                </div>
                <div class="meta">
                    <div class="address">
                        {{apartment.address}}
                    </div>
                    <div class="postdata">
                        Zip: {{apartment.locationid.zip}}
                        City: {{apartment.locationid.city}} <br>
                        {{apartment.locationid.country.country}}
                    </div>
                    <div class="size">
                        {{apartment.size}} m2.
                    </div>
                    <div class="price">
                        $ {{apartment.listings.price}} .
                    </div>
                </div>
            </div>
            {% endfor %}

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}